try {
    Prove9.Run();
}
catch (Exception exception) {
    Console.WriteLine(exception);
}